#
#Fri Apr 18 11:49:11 COT 2025
acceptInsecureCerts=false
browserName=MicrosoftEdge
ms\:edgeOptions={args\=[start-maximized, test-type, ignore-certificate-errors, incognito, disable-infobars, disable-gpu, disable-default-apps, disable-popup-blocking, remote-allow-origins\=*], extensions\=[]}
